### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by jrevels** [JuliaArrays/StaticArrays.jl#142]
Being the swashbuckling Julian that I am, I decided to throw caution to the wind and implement https://github.com/JuliaDiff/ForwardDiff.jl/pull/215 against StaticArrays master rather than latest tag (mainly because I wanted https://github.com/JuliaArrays/StaticArrays.jl/pull/127).

Would it be possible to tag a new release here, so that I can get Travis passing for https://github.com/JuliaDiff/ForwardDiff.jl/pull/215?

Thanks!

**Comment by c42f** [comment]
Nice! I think master is in reasonable shape for a tag.  Looks like it will be 0.5.0, with #127 a breaking change.

Release notes roughly as follows -

Bug fixes:
#124 (indexing with zero sized arrays)
#139 (Type inference workaround for index_sizes)

Minor feature additions and fixes
#128 (Fixes for additional fancy linear indexing)
#131, #140 (Return SVector from some mixed static/abstract array operations)

Breaking changes:
#127 (Unify SArray, SMatrix, SVector - `Tuple` must now be passed as an SArray size parameter)

It looks like bd3236a could do with a little more test coverage.

@andyferris do you think we're in reasonable shape to tag?

**Comment by c42f** [comment]
@andyferris what do you want to do with #134 vs just tagging right away (probably with #138 merged too though).

If we go right ahead with #134, we haven't given any time for stabilization before releasing a big breaking change... which doesn't seem ideal.  On the plus side, it means users can get the breakage of #127 and #134 over together, and they are rather related.

**Comment by tkoolen** [comment]
Just my two cents: I would prefer a 0.4.1 without #134, as this would be the quickest way to get a version of RigidBodyDynamics out that supports Julia 0.6-. I need compatible versions of StaticArrays and Rotations that work on 0.6-, and I need https://github.com/JuliaArrays/StaticArrays.jl/pull/139.

**Comment by andyferris** [comment]
My preference is to merge #134 first (or at least get feedback if it is desirable). Otherwise we'd need 0.5.0 and 0.6.0 and yeah, it's related to Keno's work.

**Comment by c42f** [comment]
Ok I reviewed #134.  It seems fairly harmless overall and worth getting merged to avoid saddling users with yet another breaking version.

**Comment by c42f** [comment]
We need to get this done, I don't want to be blocking people - I'll tag and release tomorrow unless there's any objections.  Updated release notes:

---

Release 0.5.0

Breaking changes:

* Unify types so that `SVector` and `SMatrix` are aliases for 1D and 2D
  `SArray`.  To make this work, the SArray size parameter must now be passed
  as a Tuple type rather than tuple instance (#127).

* Add size information to the base `StaticArray` type and type aliases, so
  that, for example, `StaticMatrix{2,2,T}` can be used for directly
  dispatching on 2x2 matrices, without messing with the Size trait (#134)

Feature additions and fixes:

* Fixes for additional fancy linear indexing (#128)
* Return `SVector` from some mixed static/abstract array operations (#131, #140)
* Bring back StaticArrays.FixedSizeArrays for julia-0.6 (#138)

Bug fixes:

* Indexing with zero sized arrays (#124)
* Type inference workaround for index_sizes (#139)

**Comment by andyferris** [comment]
Sounds great to me!

**Comment by andyferris** [comment]
I guess there are a couple of bug fixes remaining?

**Comment by andyferris** [comment]
@c42f please consider #147 and #148 before tagging - I think they are ready to go.

**Comment by andyferris** [comment]
There's still #125 but I'm happy to tag first and bugfix that one afterwards.

**Comment by c42f** [comment]
Nice, thanks Andy, I'll review those asap.

Definitely let's put further bug fixing into the next release... as long as there's not *more* than the previous release I'm happy ;-)

**Comment by c42f** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8999

**Comment by jrevels** [comment]
Thanks again to both of you for your hard work making such a useful package!
