### ISSUE TITLE
Change in subtyping for `StaticVector` from Julia 0.5 to 0.6

### ISSUE THREAD

**Issue by dpsanders** [JuliaArrays/StaticArrays.jl#152]
On recent master of Julia 0.6 I have to write
```jl
immutable IntervalBox{N,T} <: StaticVector{N, Interval{T}}
    data::NTuple{N,Interval{T}}
end
```

whereas on Julia 0.5 I had
```jl
immutable IntervalBox{N,T} <: StaticVector{Interval{T}}
    data::NTuple{N,Interval{T}}
end
```
(without the extra `N` in `StaticVector`).

How can I write something that will work for both 0.5 and 0.6 (or how can I test which version of `StaticArrays` etc.)?

**Comment by c42f** [comment]
Good question.  In our packages which depend on `StaticArrays` (eg, `Rotations`), we've been cutting over to julia-0.6 and stopping the support for julia-0.5 in one release, but this isn't great and I'd love to have a better option.  There's no immediate solution to this problem, but I can think of some ideas:

1. Backport the change which introduced these type parameters to the StaticArrays-0.3 branch, which is the maintenance branch for julia-0.5 support.  You could then support both julia-0.5 and 0.6 using something like the StaticArrays version range `StaticArrays 0.3.2 0.4- 0.5`
2. Add an `@sa_compat` macro to both StaticArrays master and the 0.3 maintenance branch, so you can at least write something like

```julia
@sa_compat immutable IntervalBox{N,T} <: StaticVector{N, Interval{T}}
    data::NTuple{N,Interval{T}}
end
```

The first option is probably better because it keeps this breaking change to the interface more compatible between versions.  But if you don't need to dispatch on the static size parameters, the second option is much easier to implement.

**Comment by timholy** [comment]
Another option would be to introduce package-specific `VERSION` numbers:
```julia
julia> module Version

       const VERSION = v"0.1"

       end
Version

julia> println(Version.VERSION)
0.1.0
```
Then you can do version tests on `StaticArrays.VERSION` in much the same way that Compat and other packages do on `Base.VERSION`. The only problem is that this constant hasn't been defined before (and with this name will default to `Base.VERSION`). One could add it to both branches and use a [more sophisticated version requirement](https://docs.julialang.org/en/latest/manual/packages.html#Requirements-Specification-1) in your interval package.

**Comment by andyferris** [comment]
I like that idea, but it seems slightly like the package manager should kneel track of this, but development versions would be fragile for `Pkg.installed("StaticArrays")`...

**Comment by timholy** [comment]
Another problem with having `Pkg` do it is you'd really like this to be a constant defined in the module, but an outside module can't assign to that binding.

I wonder if this is a job for attobot, something along the lines of "if a `src/version.jl` file exists, attobot updates the version number in the file, typically by making a commit to the repo, before tagging the release." CC @simonbyrne.

**Comment by c42f** [comment]
Ideally it seems useful for *all* packages which are part of the standard package system to have an accessible version number, but versioning in the source code seems like asking for trouble to me: unless it's completely automated, version tags will sometimes be out of sync with the `VERSION` in the source, just like REQUIRE tends to be, but more problematic. Given the number of ways there are to use git, it doesn't seem likely that this will be automated away.  You also can't add version information to previously tagged packages.

**Comment by dpsanders** [comment]
Is a reasonable solution just to check the Julia version for 0.5 vs 0.6?

**Comment by dpsanders** [comment]
That seems to work (although it's ugly).

**Comment by c42f** [comment]
I started backporting the main API changes to StaticArrays-0.3 (for julia-0.5 support), but there's a lot of conflicts.  Will see how I go.

**Comment by c42f** [comment]
This issue seems obsolete... and it seems I never did finish that port.
