### ISSUE TITLE
StaticArrays v0.6 returns different type when using arithmetic

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/StaticArrays.jl#162]
```julia
u0 = zero(MVector{2,Float64}) # Creates an MVector
u0 .+ 1 # Creates an SVector
```

Is this intended?

**Comment by andyferris** [comment]
Generally, yes that is intentional, as it's assumed that all the intermediate operations should be as fast as possible, and in the rare cases that mutability is helpful (I've managed to remove all the mutable cases from my code) you can pretty cheaply copy the result to the heap by converting the output to a `MVector` or whatever.

As a general rule, I would create as few mutable objects as necessary, and mutate them:

```julia
u = zero(MVector{2})
u .= u .+ 1
```

However, it seems rare to me that you want more than a couple of mutable objects. (Of course, you can make a `v::Vector{SVector{2,Float64}}` and mutate as many of them as you want - by replacement via `@inbounds v[i] = u .+ 1`, which is fast/seems to invoke SSE/AVX).

**Comment by ChrisRackauckas** [comment]
Thanks for the explanation. This showed up only because I wanted to make an MVector that started at 2 for a simulation, and I got lazy with the initialization. I thought it was quite peculiar behavior, seeing that you can just convert after, this behavior makes sense. This also might be a good way to find "performance bugs" too: if you forget to mutate something, this will change things to SVectors and type-checks will error.  So maybe this is a feature and I didn't realize it at first 👍. You may want to mention this in the README, especially since it's a breaking change from pre-v0.6.
