### ISSUE TITLE
Promotion rules should follow Vector

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/StaticArrays.jl#176]
The following is inconsistent:
```julia
julia> promote_type(SVector{2,Float64},SVector{2,Complex128})
StaticArrays.SArray{Tuple{2},T,1,2} where T

julia> promote_type(Vector{Float64},Vector{Complex128})
Array{Complex{Float64},1}
```

**Comment by andyferris** [comment]
Nice catch. We should fix this.

**Comment by daanhb** [comment]
I ran into the same (or a very similar) issue today. It seems `promote_rule` is not defined for `SVector` like it is for an `Array`:
```
julia> promote_rule(SVector{1,Float64},SVector{1,BigFloat})
Union{}

julia> promote_rule(Array{Float64,1},Array{BigFloat,1})
Array{BigFloat,1}
```

The line implementing `promote_rule` for `Array` is (on current master) [this](https://github.com/JuliaLang/julia/blob/master/base/array.jl#L337]) one, I think:
```
promote_rule(::Type{Array{T,n}}, ::Type{Array{S,n}}) where {T,n,S} = Array{promote_type(T,S),n}
```

**Comment by daanhb** [comment]
Meanwhile I tried it out and it seems like the analogue for `SArray` would work. Adding this line:
```
Base.promote_rule(::Type{SArray{S,T,N,L}},::Type{SArray{S,U,N,L}}) where {S,T,U,N,L} = SArray{S,promote_type(T,U),N,L}
```
to `SArray.jl` seems to fix this issue and at least does not seem to affect the tests (I only ran the tests of the StaticArrays package).

**Comment by c42f** [comment]
This is the right idea.  We can get it to work for all `StaticArray` subtypes with something like:

```julia
Base.promote_rule(::Type{SA1}, ::Type{SA2}) where {S,T,U,N, SA1<:StaticArray{S,T,N}, SA2<:StaticArray{S,U,N}} = similar_type(SA1, promote_type(T,U), Size(S))
```

Can you describe the high level use case where you ran into this problem?  This will help writing us some relevant tests.

**Comment by c42f** [comment]
Hmm.  The fix I've got in #215 doesn't preserve mutability.  Is that going to be a problem?  We're going to need a more nuanced `similar_type` soon by the looks of things.

**Comment by daanhb** [comment]
Thanks for your quick response! I was building a system to embed spaces in larger spaces, for use in geometry computations. The complex plane can be identified with the euclidean plane R^2 for example, and R^2 can be embedded in R^3 by zero-padding. This is not something you want to happen automatically, so it is separate from the usual Julia conversion and promotion system. However, I was reusing existing promotions and conversions, so that a complex number with `Float64` real and imaginary part would also promote to R^2 with `BigFloat`s, for example. (It is not working currently because I have yet to find a way to deal with possible loops in the graph of embeddings).

Anyway, `SVector` is of course extremely useful for a vector in R^N. For this purpose it is sufficient that an `SArray` implements the promotion interface like a regular `Array` does. Specifically, I was using `promote_type(S,T) == T` to check whether `S` promotes to `T`. If so, I assume that `convert(T, x)` for x of type S is implemented. The conversions of `SVector` to wider numeric type seem to work, but `promote_type` did not. Some tests could be:
```
promote_type(SVector{1,Float64}, SVector{1,BigFloat}) == SVector{1,BigFloat}
promote_type(SVector{2,Float64}, SVector{2,Complex128}) == SVector{2,Complex128}
```
for the promotion rules, perhaps with other values of N and for some `SArray`'s too.

For completeness, the conversions could also be tested (if they aren't already):
```
typeof(convert(SVector{1,BigFloat}, SVector(1.0))) == SVector{1,BigFloat}
typeof(convert(SVector{1,Complex128}, SVector(1.0))) == SVector{1,Complex128}
```
The latter tests already pass, and I think #215 is sufficient for the former.

I have not ventured into mutable arrays myself and I currently see no need for them in this project. But if they're a problem, for the time being I can get by by simply adding the `promote_rule` to my own code. It seems `StaticArrays` itself does not rely on promotion because e.g. `+` is implemented in terms of `map`, and promotion happens elementwise. (Presumably this is more efficient in some cases.)

**Comment by c42f** [comment]
Thanks for the detailed explanation!

> e.g. + is implemented in terms of map, and promotion happens elementwise. (Presumably this is more efficient in some cases.)

I don't think it was more efficient, but one very nice thing about doing it this way is we get type inference to do the work of inferring the new eltype, but without having to define any `promote_op`-like machinery ourselves, and without a need to explicitly call inference.  The new eltype comes for free when you supply the elements with a particular type at construction time :-)

**Comment by daanhb** [comment]
That is good to know about, I did not realize `map` had become this powerful. I'll start using it more :-)

**Comment by c42f** [comment]
Ok, I've hopefully sorted this out in #215.  We ended up using a less generic version of `promote_rule` which I implemented for `SArray`, `MArray` and `SizedArray`.
