### ISSUE TITLE
Indexing a SArray with a range produces a MArray

### ISSUE THREAD

**Issue by lstagner** [JuliaArrays/StaticArrays.jl#21]
```
julia> a = @SArray rand(2,2)
2×2 StaticArrays.SArray{(2,2),Float64,2,4}:
 0.84171   0.807997
 0.427424  0.743513

julia> a[1:1,:]
1×2 StaticArrays.MMatrix{1,2,Float64,2}:
 0.84171  0.807997

julia> a[1,:]
2-element StaticArrays.SVector{2,Float64}:
 0.84171 
 0.807997
```

**Comment by andyferris** [comment]
Thanks for pointing this out, but I'd also like to know what you were expecting?

*I* was expecting an `Array` but there is known issue (#22) causing `MArray` to pop up. If you were expecting an immutable static array (`MArray` or `MMatrix`) then you need to type:

    a[(1,), :]

since the size of the output array is known to the compiler (the tuple length is inferrable).

I'd like to support ranges but unfortunately it won't work properly with the Julia compiler.

**Comment by andyferris** [comment]
This now returns `Array` on master. I'll close the issue.
