### ISSUE TITLE
`similar(staticarray, newsize)` produces a statically sized array

### ISSUE THREAD

**Issue by andyferris** [JuliaArrays/StaticArrays.jl#22]
This is inefficient since the new size won't be known to the compiler, and `Array` would be faster. While speculative, future compiler enhancements might lead to proper constant propagation in this case, I think we should make this return an `Array` for now.

Should we introduce `similar(array, Val{newsize})`? It clashes with a method in base, but I think this usage makes more sense. @timholy?

**Comment by timholy** [comment]
Given that one could create an array of `Val` objects, we probably shouldn't co-opt that meaning of `similar`. How about introducing a specific type, like `SDims{newsize}`? Since that type doesn't yet exist, there's no code that could possibly break.

We might conceivably want `SIndices{newinds}` someday, so being able to dispatch on more than one type will also be nice.

**Comment by andyferris** [comment]
> How about introducing a specific type, like SDims{newsize}? Since that type doesn't yet exist, there's no code that could possibly break.

This is a bit like Stefan's proposal in JuliaLang/julia#18161. 

Maybe `Dimensions{(d1, d2,...)}` ?

**Comment by timholy** [comment]
That would be fine. Base has `Dims`, and I was making that Static :stuck_out_tongue: . But no objections to this version.

**Comment by timholy** [comment]
FYI there's also a typealias in base already called `Indices` which won't do what it would need to do here. Though really one could use `Dimensions` for both of them, having it contain either an `NTuple{N,Int}` or `NTuple{N,AbstractUnitRange}`.

**Comment by andyferris** [comment]
> That would be fine. Base has Dims, and I was making that Static :stuck_out_tongue: . But no objections to this version.

Oh I get it now... :)

> FYI there's also a typealias in base already called `Indices` which won't do what it would need to do here. Though really one could use Dimensions for both of them, having it contain either an `NTuple{N,Int}` or `NTuple{N,AbstractUnitRange}`.

So `Indices` helps with the non-1-based indexing?

In general, I have been wondering whether any isbits, indexable collection could be the indices... so `SVector{3}` would become `SVector{1:3}` but we could also have `SVector{(:red, :green, :blue)}`.

**Comment by timholy** [comment]
Maybe yes. But one constraint needs to be contiguity, if the index type has such a notion. In other words, `[1,2,4]` would be right out.

**Comment by andyferris** [comment]
Right... I guess this comes back to the old question about the difference between an array and a `Dict`. So what is the *current* definition of an array dimension? Any `UnitRange`? Would you like to extend that in any way?

**Comment by timholy** [comment]
At present, any `AbstractUnitRange` works (see https://github.com/timholy/CustomUnitRanges.jl). I'm all in favor of thinking about how to extend the notion of indices, but with full awareness of the potential for ambiguities (by which I mean potential for multiple conflicting meanings, e.g., my oops fixed in https://github.com/alsam/OffsetArrays.jl/pull/12, or the issue re linear indices addressed by the addition of [linearindices](http://docs.julialang.org/en/latest/devdocs/offset-arrays/#linear-indexing-linearindices)) or performance costs of generalizations.

You probably already saw https://github.com/JuliaLang/julia/issues/10064#issuecomment-241781050.
