### ISSUE TITLE
Devectorization of static array expressions?

### ISSUE THREAD

**Issue by dbeach24** [JuliaArrays/StaticArrays.jl#23]
I'm interested in knowing if there are any plans to support devectorization for expressions involving statically sized arrays.  As a test, I tried using this in combination with the Devectorize.jl package, for example:

```jl
using StaticArrays
using Devectorize
x = SVector(1.0, 2.0, 3.0)
@devec y = x .+ x .+ x
```

Unfortunately, `y` comes out as an `Array{Float64, 1}`, not a static vector.  Are there any plans to support such functionality in this package, or does that belong elsewhere?

**Comment by andyferris** [comment]
OK, on one hand broadcast fusion *should* deal with that automatically - not sure if we need to wait for 0.6 for that or not. 

On the other hand, because (a) things live on the stack, (b) all basic functions are unrolled and inlined, and (c) LLVM is relatively intelligent, there isn't really much penalty for `(x + x) + x` vs a specialized `+(x,x,x)`. Check out:

```julia
julia> f(x) = x+x+x
f (generic function with 1 method)

julia> @code_native f(x)
	.text
Filename: REPL[22]
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 10
	vmovsd	(%rsi), %xmm0           # xmm0 = mem[0],zero
	vmovsd	8(%rsi), %xmm1          # xmm1 = mem[0],zero
	vaddsd	%xmm0, %xmm0, %xmm2
	vaddsd	%xmm1, %xmm1, %xmm3
	vmovsd	16(%rsi), %xmm4         # xmm4 = mem[0],zero
	vaddsd	%xmm4, %xmm4, %xmm5
	vaddsd	%xmm0, %xmm2, %xmm0
	vaddsd	%xmm1, %xmm3, %xmm1
	vaddsd	%xmm4, %xmm5, %xmm2
	vmovsd	%xmm0, (%rdi)
	vmovsd	%xmm1, 8(%rdi)
	vmovsd	%xmm2, 16(%rdi)
	movq	%rdi, %rax
	popq	%rbp
	retq
	nopl	(%rax)
```

Just six additions and a bit of register shuffling - not sure what else you might want?

However these optimizations won't be true for `MVector`. There may be an intermediate allocation, and LLVM won't mess around with instructions to the heap very much.

Final caveat: fast methods for `map` and `broadcast` have not been implemented beyond two inputs. That is definitely on the agenda, though. When I do that and broadcast fusion is implemented fully for all `.` operators in Julia 0.6, you should get good results for `MVector` etc automatically.

**Comment by andyferris** [comment]
As for supporting *Devectorize.jl*, I wonder why they aren't calling `similar`?

**Comment by andyferris** [comment]
Oh and look what happens when you enable `-O3`:

```julia
ferris@andy-nuc:~/dev/researchhpc/TreeClustering$ julia -O3
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> using StaticArrays

julia> f(x) = x+x+x
f (generic function with 1 method)

julia> x = SVector(1.0, 2.0, 3.0)
3-element StaticArrays.SVector{3,Float64}:
 1.0
 2.0
 3.0

julia> @code_native f(x)
	.text
Filename: REPL[2]
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 10
	vmovupd	(%rsi), %xmm0
	vaddpd	%xmm0, %xmm0, %xmm1
	vmovsd	16(%rsi), %xmm2         # xmm2 = mem[0],zero
	vaddsd	%xmm2, %xmm2, %xmm3
	vaddpd	%xmm0, %xmm1, %xmm0
	vaddsd	%xmm2, %xmm3, %xmm1
	vmovupd	%xmm0, (%rdi)
	vmovsd	%xmm1, 16(%rdi)
	movq	%rdi, %rax
	popq	%rbp
	retq
	nopl	(%rax,%rax)
```

Even fewer instructions (SSE/AVX).

**Comment by dbeach24** [comment]
I didn't realize how well LLVM could optimize this code.  Seems like there's really no reason to be worried about manual or macro-based devectorization in many cases, which is great news.

Thanks!

**Comment by andyferris** [comment]
Right, thanks. :)
