### ISSUE TITLE
Allow @SVector comprehension to eval range with locals?

### ISSUE THREAD

**Issue by dbeach24** [JuliaArrays/StaticArrays.jl#26]
Because the `@SVector` macro does not evaluate the range using the local scope, I find myself transforming code like this:

``` jl
function mytransform{N}(x::SVector{N})
    @SVector [x[i] * i for i=1:N]
end
```

into this:

``` jl
function mytransform{N,T}(x::SVector{N,T})
    SVector{N,T}(ntuple(i -> x[i] * i, N) ...)
end
```

I'm not sure if the second form is as efficient, but in either case, the first version is far easier to read.

Is there any chance that `@SVector` comprehensions can be made to support local variables in the range?  Or, is there some other way I should be writing this?

**Comment by c42f** [comment]
Normally `@SVector` unrolls the generator expression, but that's not possible in this case without extra compiler support since `N` isn't a literal known to the macro.

However, the second version can be written directly with a generator which isn't too bad:

```julia
function mytransform{N,T}(x::SVector{N,T})
    SVector{N,T}(x[i]*i for i=1:N)
end
```

From a quick look at code_native, it seems that a call is still being made so this probably won't be super fast.  It may be possible to improve the codegen with an extra generated function, to unroll once `N` is known?

**Comment by andyferris** [comment]
@dbeach24 This is something I'd *like* to do but as @c42f mentions its a little difficult with current compiler support. I have an idea for one hack which would end up using a call and a loop yet AFAIK it still should be faster to write
```
function mytransform{N,T}(x::SVector{N,T})
    @inbounds return SVector{N,T}(x[i]*i for i=1:N)
end
```
as @c42f we need an `@inbounds` somewhere for the `x[i]` (otherwise I don't know why it would call, but if that doesn't work then I should investigate).

Another approach is to have a *statically valued* thing like `SUnitRange{1, N}() <: StaticVector{Int}` and call `map` on it. This will probably be implemented sometime soonish.

To my understanding, this one:
```
function mytransform{N,T}(x::SVector{N,T})
    SVector{N,T}(ntuple(i -> x[i] * i, N) ...)
end
```
should be performant up until N = 16 and slow afterwards, The compiler people are interested in making this fast for all N (a longer term goal, however).

**Comment by andyferris** [comment]
I've started to look at this in #30

**Comment by andyferris** [comment]
OK I've had a thought. First we implement function initialization for all `StaticArrays` such that
```julia
SVector{N}(f::Function)
```
populates `SVector{N}((f(1), f(2), ..., f(N))` (and so-on for higher dimensional arrays). This would be useful in its own right.

Furthermore, transform this:
```julia
@SVector [f(i) for i = inds]
```
into this
```julia
N = size(inds) # can we check/enforce if this is statically determinable? E.g. size(typeof(1:10)) is OK.
SVector{N}(j -> f(inds[i]))
```
We can assume the `inds` collection is an indexable collection, since it's useless (speed wise) if its size is unknown...

It would help syntactically if we made `colon(a,b)` into a `@pure` function, as well as `size(::UnitRange)`.

**Comment by andyferris** [comment]
BTW @dbeach24 the `...` in the below is unnecessary (in fact, a tuple is desirable) and you should use `ntuple(f, Val{N})`.
```
function mytransform{N,T}(x::SVector{N,T})
    SVector{N,T}(ntuple(i -> x[i] * i, N) ...)
end
```

So this is fast (up to N = 15 or so)
```
function mytransform{N,T}(x::SVector{N,T})
    SVector{N,T}(ntuple(i -> x[i] * i, Val{N}))
end
```

**Comment by shorty66** [comment]
The construct in question
```julia
function mytransform{N}(x::SVector{N})
    @SVector [x[i] * i for i=1:N]
end
```

can be written without the macro like this:

```julia
function mytransform{N}(x::SVector{N})
    SVector([x[i] * i for i=1:N]...)
end
```

Though i feel like the `SVector()`-constructor should be able to handle arrays without the splatting.

**Comment by garrison** [comment]
Slightly OT: In two comments above it is mentioned that the following workaround should work
```julia
function mytransform{N,T}(x::SVector{N,T})
    SVector{N,T}(x[i]*i for i=1:N)
end
```
however, when I call it as `mytransform(@SVector [1,2,3])`, I get `ERROR: No precise constructor for SVector{3,Int64} found. Length of input was 1.`

Did passing a generator to the `SVector` constructor in this way work in a previous version of StaticArrays?  (Should this be considered a regression?)

**Comment by andyferris** [comment]
We've never *robustly* supported generators in the past. It's something I'd like to improve on, though. Hmm...

**Comment by c42f** [comment]
I think this issue is basically the same as #97
