### ISSUE TITLE
Fully FieldVector Broadcasts Drop Names

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/StaticArrays.jl#314]
Using #313 for simplicity:

```julia
a = @FVector Float64 [a,b,c] [1,2,3]
b = a.+a
c = @MFVector Float64 [a,b,c] [1,2,3]
d = c.+c
```

The type of `b` here is `SVector` and the type of `d` here is `SVector` as well. It would be nice if in this case where the types are all known to be the same `FieldVector` that it can stay that `FieldVector` so that the return type has the same naming.

**Comment by andyferris** [comment]
You need to overload `similar_type`. Please note that you have exactly the same behavior in standard (non static) `AbstractArray`s except in `Base` you need to overload `similar`, in order to get an array of the same type out of methods in `Base`.

**Comment by ChrisRackauckas** [comment]
Should this be done on the abstract type?

**Comment by ChrisRackauckas** [comment]
Overloading `similar_type` didn't work.

```julia
StaticArrays.similar_type(a::T) where T<:FieldVector = T
similar_type(a)
b = a.+a

3-element SVector{3,Float64}:
 2.0
 4.0
 6.0
```

**Comment by andyferris** [comment]
Oh, sorry, the docs aren't clear enough here! For 3 vectors, please overload:

```julia
similar_type(::Type{<:MyFieldVector}, ::Type{T}, ::Size{(3,)}) where {T} = MyFieldVector{T}
```
The 3-argument form is what gets used in practice.

You can't overload all of `FieldVector` since (a) sometimes you need a matrix or different sized vector, so that won't work, and (b) some users may wish to implement a custom type which has special properties (I'm thinking *Rotations.jl* which has orthogonal matrices) and thus should fall back to `SVector` when arbitrary transformations occur.

**Comment by andyferris** [comment]
> Should this be done on the abstract type so that way by default this works properly?

To follow up, we copy the pattern from `Base` where things fall back to `Array` unless otherwise specified. (Generally, we also aim to follow the design of `Base` as closely as possible, and in this case I think this has been considered and came to the same conclusions as I mention above).

**Comment by andyferris** [comment]
Did overloading that method work for you?

**Comment by ChrisRackauckas** [comment]
It worked
