### ISSUE TITLE
MVector*MVector' returns an SMatrix

### ISSUE THREAD

**Issue by dmbates** [JuliaArrays/StaticArrays.jl#331]
I have noticed that some operations on `MArray`s return `SArray`s.  Is this intentional?
```
julia> Pkg.status("StaticArrays")
 - StaticArrays                  0.6.4

julia> using StaticArrays

julia> v = @MVector ones(2)
2-element MVector{2,Float64}:
 1.0
 1.0

julia> v*v'
2×2 StaticArrays.SArray{Tuple{2,2},Float64,2,4}:
 1.0  1.0
 1.0  1.0
```

**Comment by andyferris** [comment]
> Is this intentional?

Yes (because `SArray` is faster and typically you don't need to mutate individual elements of results of computations). This is controlled by `similar_type` (which is possible to overload). However, we are currently revisiting that decision over at #327 for v1.0 of Julia.

I'll close this issue and you may contribute over at #327.
