### ISSUE TITLE
hcat allocations with Julia master

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#388]
```julia
using StaticArrays, BenchmarkTools
 x = zeros(SVector{3})
@btime hcat($x, $x, $x, $x, $x, $x)
```

On 0.6.2:

```julia
  8.691 ns (0 allocations: 0 bytes)
3×6 StaticArrays.SArray{Tuple{3,6},Float64,2,18}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
```

On 8 day old master:

```julia
455.411 ns (10 allocations: 688 bytes)
3×6 SArray{Tuple{3,6},Float64,2,18}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
```

3x5 is fine, so must be reaching a compiler limit.

**Comment by tkoolen** [comment]
> Have you checked whether this is from hcat(::SMatrix{3,5}, ::SVector{3}) or hcat(::StaticArray...)?

It's the latter. (issue still present by the way)

**Comment by andyferris** [comment]
Note that the latter (the splatting problem) will remain a persistent problem for some time. Generally, it's best to avoid recursive calls to splatting functions with unbounded number of inputs, because the compiler has to choose a limit for inlining and beyond that the recursive method costs O(N^2) and may have other inefficiencies (allocations, loss of type information, etc).

So we should either rewrite a generic, non-recursive `hcat` or else put in special methods for `reduce(hcat, Tuple{Vararg{StaticArray}})` or some such, similar to how `Base` is going (even usage of `hcat(::Array...)` is discouraged for efficiency reasons).
