### ISSUE TITLE
Broadcasting should return the same type for a subtype of StaticVector

### ISSUE THREAD

**Issue by dpsanders** [JuliaArrays/StaticArrays.jl#406]
Consider 
```jl
julia> using IntervalArithmetic

julia> x = IntervalBox(1..1, 2..2)
[1, 1] × [2, 2]

julia> sin.(x)
2-element StaticArrays.SArray{Tuple{2},IntervalArithmetic.Interval{Float64},1,2}:
 [0.84147, 0.841471]
 [0.909297, 0.909298]
```
I would really like `sin` etc. to return an `IntervalBox`, which is defined as
```jl
struct IntervalBox{N,T} <: StaticVector{N, Interval{T}}
    data::NTuple{N,Interval{T}}
end
```
How would I go about this?

**Comment by andyferris** [comment]
You need to overload `StaticArrays.similar_type(InputType, NewElementType, NewSize)` so that the internal StaticArrays functions know to use this.

Keep in mind that this burden to do this is on the user, but that this is true for all `AbstractArray`s. (In `Base`, we tend to create a mutable instance via `similar` and in static arrays we tend to find the (immutable) type via `similar_type`).

Please note: I would caution against using a subtype of `AbstractArray` if you are going to change the meaning of `in` and `issubseteq` and so-on. Semantically, according to the `AbstractArray` interface, the two elements `in` your `IntervalBox` are `1..1` and `2..2`. I would suggest "going it alone" and making your own `IntervalBox` interface with appropriate definitions for `in`, `issubset`, `union`, `intersect`, `map`, `broadcast`, and so-on. (Also don't be afraid of overloading the `empty` function in Julia v0.7 https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/master/src/multidim/intervalbox.jl#L44).

**Comment by dpsanders** [comment]
OK thanks.

So are you suggesting that I define `IntervalBox` as *containing* an `SVector`, rather than inheriting from it?

**Comment by andyferris** [comment]
Yes, sure. Though in many cases even an `NTuple` would be sufficient, but whatever is most ergonomic for your use case.

**Comment by c42f** [comment]
I think you've long since sorted this out in `IntervalArithmetic`, but let use know if there's still something that needs doing here.
