### ISSUE TITLE
Matrix multiplication slower in 0.7

### ISSUE THREAD

**Issue by Datseris** [JuliaArrays/StaticArrays.jl#462]
```
using StaticArrays
julia> A, B = rand(SMatrix{3,3}), rand(SMatrix{3,3})
julia> @btime $A*$B;
julia> @btime $A*$B;
  8.210 ns (0 allocations: 0 bytes)
```
however on Julia 0.7, with `StaticArrays v0.8.1` I get
```
julia> @btime $A*$B;
  9.442 ns (0 allocations: 0 bytes)
```

**Comment by andyferris** [comment]
Ok - can you please give us `@code_native` or some other breadcrumbs like compile targets, optimization level, etc?

**Comment by Datseris** [comment]
Do you mean that you do not see the same regression? Then it could just be random noise...?

I used default versions of Julia in both cases. I don't know what is a compile target, and I think the default level is to always have optimization `-O 3`, right?

I can give you the native:
https://gist.github.com/Datseris/f552dc257c6755cfe3ca50531b140d9b

**Comment by fredrikekre** [comment]
I can't repro, and get the same generated code on both 0.6 and 0.7.

**Comment by Datseris** [comment]
@fredrikekre thanks for contributing to the discussion. Which generated code you get on 0.7? The one I posted for 0.6, or the one I posted for 0.7? The one for 0.6 is significantly smaller.

**Comment by tkoolen** [comment]
Here are a few datapoints.

### Test code

```julia
using StaticArrays, BenchmarkTools
@btime A * B setup = begin
    A = rand(SMatrix{3, 3})
    B = rand(SMatrix{3, 3})
end
```

### Setup

For 0.6.3: download official release, rebuild system image using https://docs.julialang.org/en/stable/devdocs/sysimg/#BuildSysImg.build_sysimg, run test code. StaticArrays 0.7.2.

For 0.7: download latest nightly (Version 0.7.0-beta.201 (2018-07-07 22:13 UTC), Commit cdd4e84ac9) and did not rebuild system image (I think this shouldn't be necessary due to multi-versioning and results seem to match a manual build from 4 days ago). StaticArrays 0.8.1.

I used two systems:

```
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

```
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

### Timing results

| CPU | Julia version | Arguments |  Time
| - |:-:| :-|:-|
| i7-3820QM | 0.6.3 | `--check-bounds=no` | 7.731 ns |
| i7-3820QM | 0.7 | `--check-bounds=no`  | 8.085 ns |
| i7-3820QM | 0.6.3 | `-O3 --check-bounds=no` | 6.801 ns |
| i7-3820QM | 0.7 | `-O3 --check-bounds=no` | 8.156 ns |
| i7-6950X | 0.6.3 | `--check-bounds=no` | 7.179 ns |
| i7-6950X | 0.7 | `--check-bounds=no` | 6.894 ns |
| i7-6950X | 0.6.3 | `-O3 --check-bounds=no` | 8.855 ns |
| i7-6950X | 0.7 | `-O3 --check-bounds=no` | 8.869 ns |

### Some conclusions

* results are very much system-dependent (for example, without `-O3` 0.7 is faster than 0.6 on the i7-6950X, while 0.7 is slower on the i7-3820QM.
* it seems that `-O3` actually hurts on 0.7 for multiplying two 3x3 matrices (significantly on the i7-3820QM), whereas it helps a bit on 0.6.

**Comment by c42f** [comment]
The differences here don't seem to be enough to fret about and we're well past 0.6 at this stage.

However! If you're still having problems and have a clear benchmark we could possibly revisit.
