### ISSUE TITLE
Implement `zero`

### ISSUE THREAD

**Issue by cortner** [JuliaArrays/StaticArrays.jl#52]
`zero` does not seem to be implemented for `SArray` and `MArray`? 

I expected it and got tripped up 2-3 times by it. I can obviously just use `@SVector zeros(3)` (e.g.) but I think it would be useful to have (a) because some people may expect it and (b) for type-agnostic algorithms.

**Comment by andyferris** [comment]
See #43 (and #42). We added this recently... as far as I know it should be working on v0.0.9. Let me know if there are any issues with the latest version.

I didn't original implement this since I had only ever used `zero` with types, and I never tried something like `zero([1,2,3])` (which is `[0,0,0]`) before writing StaticArrays. But the additive identity makes sense.

The most useful thing to me is now `zeros(SVector{3,Float64}, 100)` now works.

**Comment by cortner** [comment]
sorry - I thought I had just updated.
