### ISSUE TITLE
maximum(A, d), sum(A, d), ... should give an SMatrix for A::SMatrix

### ISSUE THREAD

**Issue by stevengj** [JuliaArrays/StaticArrays.jl#65]
Currently, this is using the generic reduction code:
```jl
julia> A = SMatrix{3,3}(rand(3,3))
3×3 StaticArrays.SMatrix{3,3,Float64,9}:
 0.0121247  0.371658  0.950669 
 0.450277   0.363499  0.0998775
 0.322925   0.158552  0.548777 

julia> maximum(A,2)
3×1 StaticArrays.MMatrix{3,1,Float64,3}:
 0.950669
 0.450277
 0.548777

julia> @which maximum(A,2)
maximum(A::AbstractArray, region) at reducedim.jl:305
```

**Comment by andyferris** [comment]
No... we shouldn't even do what is happening now (return `MMatrix`)! It's not type-stable, and I plan on fixing this (#22) soon.

To do this *properly*, we would need something like https://github.com/JuliaLang/julia/issues/17880 (simultaneous inlining and inference) so that we have some way of constant-propagating the dimension you are selecting to reduce over inside another function.

Is this a function you find you use a lot? I almost never do, but maybe that is just me. (I *would* use things like `sum(::Vector{SVector{3,Float64}})` for instance - `reinterpret()` is useful for this stuff). If someone absolutely needs this, we can add a `Val` version, e.g. 
```julia
sum(rand(SMatrix{3,3}), Val{2})
```

**Comment by stevengj** [comment]
I'm using it in a package I'm working on, but it's not that performance-critical.

**Comment by wsshin** [comment]
Generated a PR addressing this: https://github.com/JuliaArrays/StaticArrays.jl/pull/86

**Comment by c42f** [comment]
Now that #86 is merged, `maximum(A,Val{2})` works.

**Comment by andyferris** [comment]
I'm going to close this... I think `maximum(A, Val{2})` is the best we can hope for at this stage.
