### ISSUE TITLE
static arrays of heterogeneous types

### ISSUE THREAD

**Issue by goretkin** [JuliaArrays/StaticArrays.jl#653]
I have run into the situation where I want a statically-sized vector (which supports `+` and scalar `*` and possibly an inner product) where the elements have different types. Instead of the type parameters having any number type representing the field and dimension, e.g. `{Float64, (4,3)}`, it would probably be `{NTuple{12, Float64}, (4,3)}` (actually not sure what's a good way to handle multi-dimensional arrays). If you wanted a 2-vector where element 1 is a `Float32` and element 2 is a `Float64`, it would be `{Tuple{Float32, Float64}, (2,)}`.

In my case, I care about heterogeneous types because I want a vector where the quantities have different units (and the types keep track of the units). For example, a state-space vector can represent the position and velocity of a particle. This object has all the vector space properties.

I'm guessing there is a lot of generic code on `AbstractArray`s that, to run efficiently, assume that `eltype` returns a concrete type. One would not be able to choose a concrete type in the case above. But if the loop through the elements were unrolled, then efficient code should still be generated. But I'm not sure if this breaks part of the implicit API of `AbstractArray`s.

**Comment by timholy** [comment]
What you're asking for isn't an `AbstractArray`. The closest you could come is to use `Union{Float32,Float64}` as the eltype.

If it must be `+`, `*`, and `dot`, your better approach is to probably define `MathTuple{T<:Tuple}` and build your own operations. But don't make it a subtype of `AbstractArray`, it's definitely not. The alternative is to call these `myplus`, `mytimes`, `mydot` and provide support for ordinary `Tuple`s.

**Comment by timholy** [comment]
I think this can be closed as a won't-fix, but lets see if others feel differently.

**Comment by c42f** [comment]
Yes, I don't think we can support this in `StaticArrays` just do to the sheer number of assumptions it would break. The fundamental problem is that supporting this efficiently would force us to unroll all operations; not merely as an implementation detail, but as a feature. I don't think we want to commit to that as we'd like to move away from doing quite so much unrolling.

It gets worse: say you've got your mixed-unit state vector working and you now want to try using it for optimization or linear algebra. Now you've probably got mixed-unit matrices as well or mixed unit higher order tensors! I don't think we have the technology to express the desired mathematics here :-/

Having said that, I do agree that what you want is mathematically reasonable; a vector with elements of different units obeys the vector space axioms. I'd encourage you to try prototyping with `YourVector <: FieldVector{Quantity}` with different field types and see how far you can get.

**Comment by c42f** [comment]
Btw, I'm not sure I quite agree with Tim that this is not an `AbstractArray`. I imagine you can put different `Quantity`s into a normal `Vector{Any}` and what you want to do may work fine. Just... very... slowly...

This is why I suggest trying with a subtype of `FieldVector`: the concrete type can support varying concrete eltypes no problems, even though the overall `eltype` is abstract.  As long as operations are fully unrolled this may not be a problem.

I do think you'll quickly run into problems whenever a reduction across dimensions of such arrays is required and the reduction isn't fully unrolled. Consider, for example, the reduction which contracts a mixed-unit vector `v` with an element of the dual vector space `u`. The type `typeof(u[i]*v[i])` would be fixed, even though `typeof(v[i])` varies, and `eltype(v)` is abstract. The only hope seems to be to fully unroll everything in this situation.

**Comment by timholy** [comment]
Fair enough; it could return `eltype(v) = Union{Float32,Float64}`. The extra information endows it with additional behavior, not a subset of behavior.

**Comment by goretkin** [comment]
Thanks for the lively discussion. I think there still isn't an explicit definition of an `AbstractArray`, but perhaps there needs to be an abstract type super type which is something that does not have the assumptions that would be broken by this. I will have to re-read the discussion more carefully to understand the points and suggestions.

As a reference, here is what dimensional analysis in linear algebra can look like: https://www.georgehart.com/research/multanal.html I am glad you brought up matrices, because the high-level conclusion from that work is that not all 2D grids of units are valid matrices. The matrix of units has to be an outer product of two vectors of units.

It would be so great to have something like this in Julia!

**Comment by andyferris** [comment]
Fascinating, @goretkin. Thanks for the link!

**Comment by timholy** [comment]
OT but a side project of mine now is to start/boost what in my opinion is a long-overdue field: "non-metric optimization theory." You can see the need for this by imagining optimization problems where each coordinate has a different physical unit from every other coordinate, and then *boom* watch all the mathematics of Nocedal & Wright (which is otherwise a beautiful book) go down in a big pile of doesn't-make-any-sense-at-all :smile:.

**Comment by c42f** [comment]
> The matrix of units has to be an outer product of two vectors of units.

That *is* interesting and thanks for the link. I was imagining that derivatives of `f(x)` where `x` is a mixed-unit vector and `f(x)` is mixed-unit would need a tensor product structure in the units. At least that means you could store tensors with units reasonably efficiently by storing the units along the axes.

Tim, that also sounds interesting and quite on topic actually. But it also seems odd; isn't it always possible to transform any optimization into a dimensionless problem and doesn't that mean there's an equivalent (more complex) unitful formulation of optimization where all the usual tricks still apply?

**Comment by mschauer** [comment]
We ran into related issues when doing a Kalman filters for a particle with location and speed, so the state vector has mixed units and the marginal covariance units are an outer product.

**Comment by timholy** [comment]
> But it also seems odd; isn't it always possible to transform any optimization into a dimensionless problem and doesn't that mean there's an equivalent (more complex) unitful formulation of optimization where all the usual tricks still apply?

You can always pick an arbitrary scaling, and that's essentially what people do. But consider this: the beloved gradient-descent (or more generally, any step in which you search "along the direction of the gradient") makes no sense from the standpoint of physical units. Say I'm minimizing the cost (measured in `$`) of drilling a hole as a function of the diameter of the bit and the rotational speed of the drill. An arbitrary `x` in my parameter space has units of `(mm, Hz)`. The gradient of my objective,  `∇f`, has units of `($/mm, $/Hz)`. Remind me again exactly how I'm supposed to evaluate the trial point `x + α*∇f`? There is no scalar `α` that makes this sum work, even if you allow it to have units. Stated differently, the gradient is a covector, not a vector, so you can't use it to construct a displacement---the only thing you're allowed to do is (1) contract it with a displacement or (2) "divide" it by the Hessian to construct a displacement.

Same issues go for trust-region methods (what does `norm(x)` mean if each coordinate of `x` has a different physical unit?), many widely-used convergence criteria (`norm(∇f) < tol`), etc. The whole intuition behind gradient-descent methods is that the gradient points in the direction of "greatest ascent," but this relies on being able to take the norm of directions and gradients (https://math.stackexchange.com/questions/223252/why-is-gradient-the-direction-of-steepest-ascent) and really you shouldn't be doing that. AFAICT nearly the entire field of optimization falls apart when you start taking these considerations seriously, except for Newton's method with line searches. And unlike trust-region methods, line search methods have an unfortunate willingness to converge to saddle points unless you do Hessian modification (which AFAICT is also "not allowed").

But I am now convinced it doesn't have to be that way---that while some methods (e.g., those that can't use Hessians) might not admit a *deterministic* non-metric implementation (you can always search in random directions, but what's the fun in that?), at least the pool of things that do have well-defined non-metric alternatives is considerably larger than what we have now. What I don't yet know is whether "mathematically sensible" (non-metric) approaches work as well or better than the methods we have now. My intuition says that ultimately they will be better because they are intrinsically invariant to changes in scale. But of course, given the many-decades head start of conventional methods it may take some time to get there.

**Comment by c42f** [comment]
> what does `norm(x)` mean if each coordinate of x has a different physical unit?

So is the "non-metric" part about avoiding making an arbitrary choice of metric? (I mean, you can always construct `norm_(x) = x*M*x` for some `M` with the correct tensor product of units. But the `M` is kind of arbitrary.)

Is it fair to say that there's nothing unique to unitful quantities here, they just happen to be a *really good* motivating example which highlights the fact that a choice of metric is often arbitrary?

Regarding scale invariance, this seems to be the usual problem of "long valleys" being hard to deal with in optimization: if you don't choose a metric in the first place, who's to say that the valley is long :-)

**Comment by timholy** [comment]
> So is the "non-metric" part about avoiding making an arbitrary choice of metric?

Yep. The idea is to never impose an arbitrary metric but only use data from `f` itself.

> Is it fair to say that there's nothing unique to unitful quantities here, they just happen to be a really good motivating example which highlights the fact that a choice of metric is often arbitrary?

Exactly. AFAICT almost all the failures of invariance (of which there are many) in standard methods come down to implicitly imposing a metric, which is why I've begun to think that "non-metric optimization" is a more useful name than "invariant optimization." But maybe I'm being too obscure. In practice they seems to be essentially the same thing.

**Comment by c42f** [comment]
I was just thinking about this again in an idle few minutes. I like the term "non-metric optimization" because it's thought provoking — considering each method to see where the metric enters and how things would break if you didn't have one.

On the other hand any serious method is adaptive in some way — I guess you could think of that as inducing a local metric which is relevant to the problem? The induced metrics can be pretty dumb to keep the number of parameters small.  Hah, here's a funny though: can one train a machine learning system to approximate the desired metric for certain "interesting classes" of problems to achieve much faster convergence? I'm thinking something along the lines of a learned version of the CG update...  Obviously that would only make sense if you had to do a huge set of the the same kind of optimizations repeatedly, but that's actually pretty common.

**Comment by c42f** [comment]
Thinking about that more, you could see this as very similar to the problem of reinforcment learning where the optimization process is an "agent" trying to make decisions at each step.

It's interesting though; people are using learned proxy models for a bunch of things, but they can be more powerful as heuristic parameters in the structure of a larger algorithm with more well understood properties. I'm thinking about how the the policy network in alpha go slots into the larger MCTS. But doing a continuous "non-metric optimization" version of that.

**Comment by cstjean** [comment]
Lovely discussion!

@timholy As your [link](https://math.stackexchange.com/questions/223252/why-is-gradient-the-direction-of-steepest-ascent) points out, the directional derivative of `f` in direction `v` is equal to `dot(grad(f), v)`. If `grad(f) = (3.0$/Hz, 4$/m)`, then the direction `v` that maximizes `dot(grad(f), v)` is along `(3Hz/$, 4m/$)`, so the units work out, no? You just need to multiply this `v` by a step size in units of `$`.
