### ISSUE TITLE
@SArray namespace hygiene

### ISSUE THREAD

**Issue by goretkin** [JuliaArrays/StaticArrays.jl#691]
```julia
using StaticArrays: @SArray
@SArray Float32[1, 2]
```

gives
`ERROR: UndefVarError: SArray not defined`

indeed:
```julia
julia> macroexpand(Main, :(@SArray [1, 2]))
:((StaticArrays.SArray{Tuple{2},T,N,L} where L where N where T)((1, 2)))

julia> macroexpand(Main, :(@SArray Float32[1, 2]))
:(SArray{Tuple{2}, Float32}((1, 2)))
```

The definition https://github.com/JuliaArrays/StaticArrays.jl/blob/a3bca3593c8ea824ebc7c95c37c6b38f52568254/src/SArray.jl#L82-L235

**Comment by c42f** [comment]
Yep this is a bug, thanks for the report.

It's not too hard to fix, but I'm wishing we could remove these macros, or at least reduce their number (eg, removing `@SMatrix`, `@SVector`).

With that in mind, what you think about the following alternative which was recently implemented in version 0.12?

```julia
julia> using StaticArrays: SA_F64

julia> SA_F64[1,2]
2-element StaticArrays.SArray{Tuple{2},Float64,1,2} with indices SOneTo(2):
 1.0
 2.0
```

It's a syntax pun of course, though not particularly different from the existing `getindex` / typed vector initialization pun that `Base` already uses.

**Comment by goretkin** [comment]
Thanks for asking what I think. My first reaction is that I did not like that alternative, since it's not orthogonal. What if I wanted a `StaticArray` of `MyQuaternion`? I admit not trying the `@SArray` macro in more complicated settings, but at least there's a syntactical way for it to work.

But I see that you could do `SA{MyQuaternion}`, so that concern is not valid.

I wonder if there would be some generic code that assumes `eltype(T[...])===T`, which would break under this pun. I think I prefer the macro over the pun, even though I've run into a few pain points with `@SArray` (related to not having enough parens, and not understanding the syntax issue) which would be fixed by this pun.

Are there other reasons you don't like the macro?

**Comment by c42f** [comment]
> I wonder if there would be some generic code that assumes `eltype(T[...])===T`, which would break under this pun

Only if there's some unexpected way for `T` to become `SA` which seems unlikely because `SA` is designed to be used as syntax. As I alluded to, this syntax pun already exists in julia:

```julia
julia> foo(T) = T[1,2]  # This is typed array construction, right?

julia> foo(rand(2,2))
0.11408848854832776  # wait, what :-D
```

We did discuss having an improved `@SA` macro vs the `SA` syntax. See the discussion at https://github.com/JuliaArrays/StaticArrays.jl/pull/633 and https://github.com/JuliaArrays/StaticArrays.jl/pull/636. It was super hard to decide but I felt that for literals it's desirable to have the shortest syntax, especially if we intend to do composition via conversion such as the syntax `MMatrix(SA[1 2; 3 4])` for `MMatrix` literals.

I don't think the macros will be going away any time soon, I think that would be quite unncessarily breaking for 1.0. But I'm still wondering about a viable transition plan for reducing the number of "constructor macros" and hoping people will be happy enough with the new syntax that we could go ahead with that eventually.

**Comment by goretkin** [comment]
> As I alluded to, this syntax pun already exists in julia

Yes, right. But this is a pun on top of that pun, I'd think. You demonstrate that Base already breaks `eltype(T[...])===T`. What about `eltype(getindex(::Type{T}, ...))===T`?

**Comment by c42f** [comment]
Indeed, it adds a third meaning which could be regarded as a good or bad move, depending on how often you happen to be writing short `SVector` and `SMatrix` literals.

However I can't think of a situation where `SA` would be likely to be used and where violating `eltype(getindex(::Type{T}, ...))===T` would actually matter. (It would matter if one might pass the `SA` type around as data, but using it directly in literal syntax seems harmless.)

**Comment by hyrodium** [comment]
The original issue was already solved.
```julia
julia> using StaticArrays: @SArray

julia> @SArray Float32[1, 2]
2-element StaticArraysCore.SVector{2, Float32} with indices SOneTo(2):
 1.0
 2.0
```
