### ISSUE TITLE
Please consider a changelog.md

### ISSUE THREAD

**Issue by Datseris** [JuliaArrays/StaticArrays.jl#698]
I can see you guys are pushing for an 1.0 which is great (especially given the massive amount of packages that depend here). Given that there are already breaking changes, e.g. `a + b` is deprecated if `a,b` are `SVector`s, please consider adding a changelog for the upcoming changes.

**Comment by KristofferC** [comment]
Isn't that just https://github.com/JuliaArrays/StaticArrays.jl/releases?

**Comment by Datseris** [comment]
Yeap, didn't realise this.

**Comment by c42f** [comment]
Yes, the changelog is maintained in the releases page (by the way, this is now standard for every package which uses the JuliaRegistrator+TagBot workflow). In addition to the automated release notes, I like to highlight significant feature additions or breaking changes.

> `a + b` is deprecated if `a,b` are `SVector`s

This is not the case! `a + b` is only deprecated when either `a` or `b` is a `Number`. We are following `Base` in removing this because it's not an operation which is usually defined in linear algebra. (The elementwise version was old functionality left over from julia 0.5 or so when we didn't have systematic broadcasting notation.)

**Comment by Datseris** [comment]
Ops, sorry, you are right, I read the deprecation notice too quickly and extrapolated half of it.

**Comment by Datseris** [comment]
> by the way, this is now standard 

Where can I read more about this? I was not made aware of this new standard, or who set it.

**Comment by c42f** [comment]
> I was not made aware of this new standard, or who set it.

It's nothing very official, just helpful functionality provided by TagBot: https://github.com/JuliaRegistries/TagBot#release-notes

**Comment by andyferris** [comment]
Yeah, it seems happy coincidence that we did it this way and now the tooling (and likely community) will follow. I’ll put that down to Chris’s excellent taste ;)

(What “standard” means in Julia is an interesting question, btw 🤣)
