### ISSUE TITLE
Arrays of static vectors

### ISSUE THREAD

**Issue by benchislett** [JuliaArrays/StaticArrays.jl#715]
I want to have a 2d array of static 3-vectors, but without fail it always seems to flatten them out.

For example, the following generates a 9x2 array of Float32, as opposed to the intended 3x2 array of SVector{3, Float32}:
```
using StaticArrays
a = SVector{3, Float32}(1, 1, 1)

arr = [a a; a a; a a] # Is 9x2, but should be 3x2?
```

**Comment by c42f** [comment]
The problem is that the syntax `[a b; c d]` is actually array concatenation syntax. So you can't use this syntax for constructing an array-of-arrays. I don't know a good solution to this.

An ugly workaround is to wrap your array `a` in another array so that one level will be unwrapped by the concatenation. You can use `StaticArrays.Scalar` for this:

```
julia> a = SA[1,2,3]
3-element SArray{Tuple{3},Int64,1,3} with indices SOneTo(3):
 1
 2
 3

julia> s = Scalar((a,))
Scalar{SArray{Tuple{3},Int64,1,3}}(([1, 2, 3],))

julia> [s s; s s]
2×2 Array{SArray{Tuple{3},Int64,1,3},2}:
 [1, 2, 3]  [1, 2, 3]
 [1, 2, 3]  [1, 2, 3]
```

Or if you don't mind some allocation you can get nicer syntax using `s = [a]`.

**Comment by c42f** [comment]
By the way, there's nothing `StaticArrays` specific about this :-)

**Comment by c42f** [comment]
I should point out that if you do want the same array repeated many times you can also use `fill(a, 3, 2)` and that's nice in this case. But if you want something like `[a b; c d]` where `a...d` are static arrays I think you may need the wrapping trick.
