### ISSUE TITLE
vcat methods for SVector, Real

### ISSUE THREAD

**Issue by Datseris** [JuliaArrays/StaticArrays.jl#757]
Please add methods for `vcat(::SVector, ::Real)`. Here is one way to do it:
```julia
vcat(a::SVector, b::Number) = vcat(a, SVector(b)) 
```

and here is another:
```julia
@generated function expand(a::SVector{D, T}, x::Real) where {D, T}
    gens = [:(a[$k]) for k=1:D]
    quote
        return SVector{$D + 1, T}($(gens...), x)
    end
end
```
don't know which is best, but I think something that useful (and simple!) should be supported/ exported by StaticArrays.jl

**Comment by Datseris** [comment]
all other naive approaches a user will do fail completely `vcat(svector, x)` returns `Array`, wile `SVector{D+1}(svector..., a)` is very inefficent.

**Comment by andyferris** [comment]
Do we have a `push` method?

**Comment by Datseris** [comment]
Oh my god, yes, you do... Sorry, it was some how impossible for me to imagine this, given that in my brain only `push!` exists, which is in-place, which can't work with SVectors...

**Comment by andyferris** [comment]
No worries, it’s a bit confusing. @c42f should we support vcat and hcat for the purpose of array literals? If so we should reopen this.

**Comment by c42f** [comment]
This is a duplicate of https://github.com/JuliaArrays/StaticArrays.jl/issues/602 though, so we can continue the discussion there.

I think we should allow hcat and vcat because indeed it's the obvious thing to do. Surprising users with things which *should work* but happen not to is not great!

The big problem is that we can't actually implement this in general: `vcat` doesn't really have dispatch machinery to infer the output array type. See https://github.com/JuliaArrays/StaticArrays.jl/issues/602#issuecomment-487428502. However it could be practical to cover the binary cases, and the cases where a `StaticArray` occurs first.

**Comment by Datseris** [comment]
Yes, agreed. Sorry that I didn't search alot, but indeed as you say, `hcat(a, x)` was the intuitive thing for me to do as well.
