### ISSUE TITLE
vector inner product via transpose-product allocates

### ISSUE THREAD

**Issue by daviehh** [JuliaArrays/StaticArrays.jl#794]
Not sure how much impact this may have on performance (e.g. inside a deeply-nested/hot loop): While static array is still faster than standard array in testing, the inner product of vectors allocates while the standard array does not:

```
a = @MVector rand(10)
b = @MVector rand(10)
@benchmark $a'*$b
```
gives
```
BenchmarkTools.Trial:
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     12.487 ns (0.00% GC)
  median time:      13.779 ns (0.00% GC)
  mean time:        15.118 ns (1.16% GC)
  maximum time:     616.073 ns (97.67% GC)
  --------------
  samples:          10000
  evals/sample:     998
```

whereas
```
p = rand(10)
q = rand(10)
@benchmark $p'*$q
```

gives

```
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     15.900 ns (0.00% GC)
  median time:      16.114 ns (0.00% GC)
  mean time:        17.177 ns (0.00% GC)
  maximum time:     127.637 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     998
```
Worth noting that `dot(a, b)` does not allocate for static array:
```
julia> @benchmark dot($a,$b)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.484 ns (0.00% GC)
  median time:      3.596 ns (0.00% GC)
  mean time:        3.790 ns (0.00% GC)
  maximum time:     57.172 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```

May be due to lazy transpose of static array does not give a static array?

```
a = @MVector rand(10)
a_tr = a'
typeof(a_tr) <: StaticArray
```

> false

```
@which dot(a,a)
```

> dot(a::StaticArray, b::StaticArray) in StaticArrays

```
@which a'*a
```

> *(u::Adjoint{T,#s662} where #s662<:(AbstractArray{T,1} where T) where T, v::AbstractArray{T,1} where T) in LinearAlgebra

**Comment by mateuszbaran** [comment]
It looks like the adjoint allocates here and it doesn't allocate on Julia 1.5 (thanks to the same change that makes views non-allocating).

**Comment by andyferris** [comment]
Yes - the Julia 1.5 improvements makes using wrappers like `Transpose` and `Adjoint` (and `SubArray`) free abstractions when they wrap GC-managed references.

The behavior in the OP for Julia 1.4 is what I would have expected, given the implementation. Since we don't have a trait or abstract supertype for covectors, we are required to use the `Base` type so other third-party packages can dispatch properly. The benchmark results for `Array` - I'm not certain what that's about (I'm not sure I always fully trust the benchmarks...)

I feel we can't do anything actionable here other than eagerly await the release of Julia 1.5 :)

**Comment by c42f** [comment]
Yep I'll close this given there's not much actionable in StaticArrays itself. Julia 1.5 (and Jeff Bezanson) to the rescue!
