### ISSUE TITLE
Performance with user-defined getproperty

### ISSUE THREAD

**Issue by J1MC83N** [JuliaArrays/StaticArrays.jl#795]
I use a SArray of length 2 as a 2D vector, calling it V2: `const V2{T} = SArray{Tuple{2},T,1,2}`
I then custom defined `getproperty` to support syntaxes like `v.x`: 
```
function Base.getproperty(v::V2, sym::Symbol)
  if sym === :x
    return v[1]
  elseif sym === :y
    return v[2]
  else
    return getfield(v,sym)
  end
  return
end
```
However, this seem to impact performance significantly: 
```
vector_V2 = V2((1,2))
@benchmark $vector_V2.x
"""
BenchmarkTools.Trial: 
  memory estimate:  64 bytes
  allocs estimate:  2
  --------------
  minimum time:     32.018 ns (0.00% GC)
  median time:      35.724 ns (0.00% GC)
  mean time:        41.199 ns (6.25% GC)
  maximum time:     2.268 μs (97.09% GC)
  --------------
  samples:          10000
  evals/sample:     993
"""
```
Such impact doesn't happen if Tuple is used in the same fashion. 
Interestingly if `v.data[#]` is used instead, the impact is reduced but still abnormal: 
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.455 ns (0.00% GC)
  median time:      1.472 ns (0.00% GC)
  mean time:        1.556 ns (0.00% GC)
  maximum time:     29.272 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```

Why is this the case? And where does the non-zero memory allocation come from?

**Comment by KristofferC** [comment]
First, you shouldn't add a `getproperty` to `SArray{Tuple{2},T,1,2}` (this is type piracy). Instead, you should make your own wrapper struct that wraps an `SArray` and overload `getproperty` on that.

The problem here is that you end up calling `getproperty` recursively (and thus break constant propagation). `v[1]` is equal to `v.data[1]` which is equal to `getproperty(v, data, 1)`. StaticArrays could change their `getindex` to `getindex(v::SVector, i::Int) = getfield(v, :data, i)` to work around this but as already stated you should probably just make a wrapper type.

**Comment by J1MC83N** [comment]
@KristofferC  I see. Thank you.

**Comment by c42f** [comment]
Another option is to create a `FieldVector` subtype thus:

```
struct V2{T} <: FieldVector{2, T}
    x::T
    y::T
end

StaticArrays.similar_type(::Type{<:V2}, ::Type{T}, s::Size{(2,)}) where {T} = V2{T}
```

or use https://github.com/SciML/LabelledArrays.jl
