### ISSUE TITLE
eachindex and SOneTo

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaArrays/StaticArrays.jl#812]
While investigating another issue I've noticed that `eachindex` on static arrays returns `Base.OneTo` while it could return `SOneTo`.  Is this intentional or just an oversight?

```julia
julia> using StaticArrays

julia> M = SA[1 2; 3 4]
2×2 SArray{Tuple{2,2},Int64,2,4} with indices SOneTo(2)×SOneTo(2):
 1  2
 3  4

julia> eachindex(M)
Base.OneTo(4)
```

**Comment by andyferris** [comment]
It would be an oversight. There is some more work to be done on the indexing side, for sure.

However I'd be curious where it matters much; `eachindex` generally used in a `for` loop (rather than an argument of `foreach` for example), and constant propagation is pretty good these days, so I'm not sure if it would affect any loop unrolling or similar?

**Comment by mateuszbaran** [comment]
I don't know if it matters anywhere and I'm not even sure if this would be an all-around improvement since I can imagine some code special-casing `Base.OneTo`.
