### ISSUE TITLE
Generalization of AbstractRange?

### ISSUE THREAD

**Issue by chakravala** [JuliaArrays/StaticArrays.jl#816]
Please see my post on discourse about generalizing `AbstractRange` objects to `SVector` inputs for multidimensional ragnes.

https://discourse.julialang.org/t/orthotope-grid-type-generalization-of-abstractrange/45072/3?u=chakravala

Either, this needs to be added to `StaticArrays` package to define the `:` constructor method without type piracy, or I need to add it to `Grassmann` and use my own custom vector input types for it.

Most likely, I’ll just add it to `Grassmann` since that has the least friction workflow for me, but if anyone else is interested, I can consider making a pull request to `StaticArrays` package.

**Comment by mateuszbaran** [comment]
What benefit does it have over the product iterator: https://docs.julialang.org/en/v1/base/iterators/#Base.Iterators.product ?

**Comment by chakravala** [comment]
Didn't know about that before, but it seems the product iterator returns tuples, which is the wrong type.

**Comment by andyferris** [comment]
Yeah - it would be nice if `Iterators.product` accepted a function, like `map`.

**Comment by stev47** [comment]
Julia base often uses `NTuple{N,AbstractRange{T}}` (at least for integer `T`) and for use with indices there is the wrapper `CartesianIndices` that supports range syntax `CartesianIndex(1,1):CartesianIndex(3,3)` already. A dedicated `Orthotope` type could improve memory layout compared to these, though I don't see a reason why it needs to use `SVectors` instead of `Tuple`s internally if it's just a multidimensional generalization of `AbstractRange{T}` in julia base.

**Comment by c42f** [comment]
So is the main thing that it'd be desirable to iterate `StaticArrays` rather than Tuples vs the other options?

I'm in two minds about this. It seems handy, but also potentially obscure and non-obvious compared to using `CartesianRange`?

**Comment by chakravala** [comment]
This issue can be closed as far as I am concerned at this point, since I am satisfied with my `Orthogrid` type in `Grassmann` now, so the rest is entirely up to you.

**Comment by c42f** [comment]
Ok, let's close this. Thanks for the discussion!
