### ISSUE TITLE
setindex! returns the wrong value

### ISSUE THREAD

**Issue by KristofferC** [JuliaArrays/StaticArrays.jl#827]
```jl
julia> a = rand(MVector{3});

julia> (c = setindex!(a, 1, 1)); c
1

julia> (c = setindex!(collect(a), 1, 1)); c
3-element Array{Float64,1}:
 1.0
 0.30794928630799046
 0.6842053878737089
```

**Comment by c42f** [comment]
Is there an official API for the return value of `setindex!`? I couldn't find it at https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array, and indeed the examples there seem to return the newly set value rather than the array. `setfield!` also returns the field value rather than the mutated object.

On the other hand, Base.Array behaves as you say and seems to be consistent about it. So I'm very happy to change this, though also confused about whether there's a "correct" option.

**Comment by tkf** [comment]
There was a similar discussion in https://github.com/JuliaLang/julia/pull/31891

It looks like the decision was that `setindex!` can return anything since the return value of `(x[i] = v)` is determined by lowering.

**Comment by tkf** [comment]
(Though I think it would have been great if `setindex!(A, ...) === A` was the part of the API.)

**Comment by KristofferC** [comment]
> Is there an official API for the return value of setindex!? 

The convention is to return the modified object.

Some more examples:

```
julia> a = rand(1,1);

julia> (c = setindex!(a, 1, 1); c)
1×1 Array{Float64,2}:
 1.0

julia> (c = setindex!(sparse(a), 1, 1); c)
1×1 SparseMatrixCSC{Float64,Int64} with 1 stored entry:
  [1, 1]  =  1.0

julia> (c = setindex!(view(a), 1, 1); c)
0-dimensional view(::Array{Float64,0}) with eltype Float64:
1.0

julia> (c = setindex!(MMatrix{1,1}(a), 1, 1); c)
1
```

**Comment by c42f** [comment]
Ok, let's follow what `Array` does. I made #832.
