### ISSUE TITLE
`reshape` should use `similar_type(a, s)` for creating the returned vector rather than `SizedArray`

### ISSUE THREAD

**Issue by chriselrod** [JuliaArrays/StaticArrays.jl#942]
See https://github.com/SciML/LabelledArrays.jl/issues/100 for examples of problems.

**Comment by mateuszbaran** [comment]
I've commented on this here: https://github.com/JuliaArrays/StaticArrays.jl/commit/1c72f5c26fd3bcc4006b38a3c583b43e65756418#commitcomment-54021728 . The problem is that `reshape` is supposed to return a view, not a copy, and `similar_type(a, s)` makes a copy. A copy is fine for immutable arrays but a rather unsafe default behavior.
